import Layout from '../components/Layout.jsx'
import PageHead from '../components/PageHead.jsx'
import SeeAlso from '../components/SeeAlso.jsx'
import Sources from '../components/Sources.jsx'
import { NetworkIcon } from '../components/Icons.jsx'

export default function Comparisons() {
  return (
    <Layout>
      <PageHead
        tag="Reception & Comparisons"
        tagColor="yellow"
        icon={NetworkIcon}
        title="Comparisons and Later Theories"
        lede="Archons, cosmic horror, tech critique — flagged as outside sources, not extensions."
      />
      <article>
        <p>
          The entries before this one reconstruct Steiner's doctrine in his own terms. This one collects,
          openly flagged as external to that doctrine, the associations other traditions and other authors
          have built around the same figures since. They're useful comparisons — not consequences of
          Steiner's cosmology, and they should be read as such.
        </p>

        <h2>The gnostic Archons</h2>
        <p>
          The term Archons belongs to early Gnosticism — texts like the Apocryphon of John and the
          Hypostasis of the Archons, recovered among the Nag Hammadi manuscripts — where they name the
          rulers of the planetary spheres, generated by the demiurge Yaldabaoth, tasked with keeping
          humanity trapped in matter. Steiner knew and discussed Gnosticism, most directly in
          <em> Christianity as Mystical Fact</em>, but he never folds the Archons into his own hierarchy of
          spiritual beings, and never presents them as subordinate to Sorat. The pairing of the two
          doctrines, common in certain corners of contemporary online esotericism, is later syncretism: a
          reasonable comparison between two "world as prison" cosmologies, not an extension of anything
          Steiner wrote.
        </p>

        <h2>Early twentieth-century cosmic fiction</h2>
        <p>
          Some currents insist on a specific point about Sorat: that it wouldn't be an alien, wouldn't
          inhabit a planet, wouldn't even be a spirit in the traditional sense — rather an intelligence
          operating on timescales and levels of awareness foreign to human ones. This is where the
          boundary with early-twentieth-century weird fiction — immense, incomprehensible entities,
          indifferent to human fate, acting across enormous stretches of time — gets genuinely thin. The
          resemblance is structural, not genealogical: two very different traditions arrive at a similar
          image answering the same unease, that of an order larger than the human and indifferent to its
          scale of values.
        </p>

        <h2>Contemporary technology critique</h2>
        <p>
          Some contemporary authors extend Sorat's name — not only Ahriman's — to phenomena like the loss
          of individual identity inside data streams, the growing fusion of human and machine, algorithmic
          control of mass behavior, the substitution of lived experience with simulation. But the sturdiest
          point of contact in the original doctrine concerns Ahriman, not Sorat, as the Michael entry
          lays out: calling a dehumanizing technology "Soratic" works well rhetorically. It remains an
          extension, not a direct consequence of the sources.
        </p>

        <SeeAlso links={[['/sorat', 'Sorat'], ['/double', 'the double, and the machines'], ['/reception', 'critical reception']]} />
        <Sources items={[
          "<em>Apocryphon of John</em> and <em>Hypostasis of the Archons</em>, gnostic texts from the Nag Hammadi library.",
          "Rudolf Steiner, <em>Christianity as Mystical Fact</em>, 1902.",
          "Contemporary popular and esoteric readings that pair Sorat, the Archons, and technology critique, treated here as objects of survey rather than doctrinal sources.",
        ]} />
      </article>
    </Layout>
  )
}
