import Layout from '../components/Layout.jsx'
import PageHead from '../components/PageHead.jsx'
import SeeAlso from '../components/SeeAlso.jsx'
import Sources from '../components/Sources.jsx'
import { CompassIcon } from '../components/Icons.jsx'

export default function Michael() {
  return (
    <Layout>
      <PageHead
        tag="The Three Powers"
        tagColor="yellow"
        icon={CompassIcon}
        title="Michael and the Falling Intelligence"
        lede="An intelligence that used to belong to the heavens, now loose inside human minds."
      />
      <article>
        <p>
          In the weekly letters Steiner wrote to Society members between Christmas 1923 and Easter 1925 —
          the last months of his life — he devotes a long sequence of texts to the archangel Michael, whom
          he calls the "administrator of cosmic intelligence." In the oldest epochs, he explains, human
          thought wasn't experienced as one's own at all: a person felt their thoughts arriving as
          revelation, channeled through Michael's power, rather than as something generated by an
          individual mind. Even as late as the age of Aristotle and Alexander, Steiner says in a lecture
          given in Vienna in August 1924, a thinking person still felt the content of their own thought as
          something disclosed to them from elsewhere — not, in his phrase, as flour from their own sack.
        </p>

        <h2>An intelligence that falls into human souls</h2>
        <p>
          After the Mystery of Golgotha, this cosmic intelligence begins slipping out of Michael's
          exclusive governance and into individual human souls on earth — becoming, gradually, the
          ordinary intellect each person today experiences as simply their own thinking. It's exactly this
          transfer, in Steiner's reading, that makes the modern age dangerous: a cosmic intelligence no
          longer directly administered by a spiritual hierarchy now sits, loose, inside human souls — at a
          stage where it can be taken. This is precisely the opening Ahriman is after: to capture, for
          material and mechanical ends, an intelligence that ought to remain free, guided by Michael,
          rather than falling into an apparatus of pure calculation.
        </p>

        <h2>1879, and Michael against the dragon</h2>
        <p>
          Steiner places the beginning of Michael's leading guidance — the age of Michael — in 1879, the
          point at which, according to the older tradition of seven ruling archangels he draws on,
          humanity is said to have left a long dark period behind and entered an age of light. It's no
          accident that the same lecture cycle that treats Sorat and the number 666 also takes up the
          theme of Michael defeating the dragon: in the original table of contents, the two themes sit
          side by side, almost two faces of a single teaching. If Sorat represents the sun-demon's attempt
          to interrupt evolution outright, Michael — the archangel of the sun — is its reverse: the
          guardian of an age that has to learn the difference between being merely diverted, which is
          Lucifer's and Ahriman's work, and being erased, which belongs to Sorat alone.
        </p>

        <SeeAlso links={[['/sorat', 'Sorat'], ['/double', 'the double, and the machines'], ['/christ-golgotha', 'Christ and the Mystery of Golgotha']]} />
        <Sources items={[
          "Rudolf Steiner, GA 26, letters to Society members (1923–1925), collected as <em>The Michael Mystery</em>.",
          "Rudolf Steiner, <em>Cosmic Christianity and the Impulse of Michael</em>, Vienna, August 21, 1924.",
          "Rudolf Steiner, GA 104, eleventh lecture: \"The Number 666, Sorat, the Sun Demon… Michael Overcomes the Dragon.\"",
        ]} />
      </article>
    </Layout>
  )
}
